name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Copy assets vào docs_dir để ảnh hiển thị đúng
        run: cp -r docs/user-handbook/assets docs/user-handbook/modules/assets

      - name: Deploy
        run: mkdocs gh-deploy --force